name: Demo (Fastlane Build)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ios-demo-build:
    runs-on: macos-15

    defaults:
      run:
        working-directory: Demo/SmartAsyncImageDemo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby (Bundler)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: Demo/SmartAsyncImageDemo

      - name: Build (Fastlane)
        run: bundle exec fastlane ios build

